[GLOBAL]
pants_version = "2.23.0"
backend_packages = [
  'pants.backend.python',
  'pants.backend.experimental.python.lint.ruff.check',
  'pants.backend.experimental.python.lint.ruff.format',
  'pants.backend.python.typecheck.mypy',
  'pants.backend.shell',
  'pants.backend.shell.lint.shellcheck',
  'pants.backend.shell.lint.shfmt',
]

[python]
interpreter_constraints = ['>=3.8']

[anonymous-telemetry]
enabled = true
repo_id = "1bb1240b-2e3b-410f-91e2-5342846ab4bc"
